cd ~/desktop
mkdir Week2
cd Week2
touch index.html
mkdir monday tuesday wednesday thursday friday
cd monday
touch physics.monday
touch english.monday
touch video_production.monday
touch math1.monday
touch ethnic_studies.monday
touch french4.monday
cd ../tuesday
touch physics.tuesday
touch english.tuesday
touch video_production.tuesday
touch math1.tuesday
touch ethnic_studies.tuesday
touch french4.tuesday
cd ../wednesday
touch physics.wednesday
touch english.wednesday
touch video_production.wednesday
touch math1.wednesday
touch ethnic_studies.wednesday
touch french4.wednesday
cd ../thursday
touch physics.thursday
touch english.thursday
touch video_production.thursday
touch math1.thursday
touch ethnic_studies.thursday
touch french4.thursday
cd ../friday
touch physics.friday
touch english.friday
touch video_production.friday
touch math1.friday
touch ethnic_studies.friday
touch french4.friday
